# version: '3.4'

# services:
#   codecartographer:
#     image: codecartographer
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     command:
#       [
#         'sh',
#         '-c',
#         "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.codecarto\__init__:app --host 0.0.0.0 --port 2000",
#       ]
#     ports:
#       - 2000:2000
#       - 5678:5678

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./src/codecarto/containers/web/Dockerfile
    ports:
      - '2000:2000'
    networks:
      - external_network
      - internal_network
    # volumnes are for quicker docker builds during development
    volumes:
      - ./src/codecarto/containers/web/api:/app/api
      - ./src/codecarto/containers/web/src:/app/src

  processor:
    build:
      context: .
      dockerfile: ./src/codecarto/containers/processor/Dockerfile
    secrets:
      - github_token
    networks:
      - internal_network
    # volumnes are for quicker docker builds during development
    volumes:
      - ./src/codecarto/containers/processor/api:/app/api
      - ./src/codecarto/containers/processor/src:/app/src

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    networks:
      - internal_network

networks:
  external_network:
    driver: bridge
  internal_network:
    driver: bridge

secrets:
  github_token:
    file: ./token.txt
