version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./src/codecarto/containers/web/Dockerfile
    ports:
      - '2000:2000'
    networks:
      - external_network
      - internal_network
    volumes:
      - ./src/codecarto/containers/web/src:/app/src

  processor:
    build:
      context: .
      dockerfile: ./src/codecarto/containers/processor/Dockerfile

    networks:
      - internal_network

  # db:
  #   image: 'postgres:latest'
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   networks:
  #     - internal_network

networks:
  external_network:
    driver: bridge
  internal_network:
    driver: bridge
