version: '3'

services:
  processor:
    container_name: processor
    image: processor
    build:
      context: .
      dockerfile: ./src/codecarto/Dockerfile
    ports:
      - '2020:2020'
    networks:
      - back_net
      - graphbase_db_net
    secrets:
      - github_token

networks:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
  graphbase_db_net:
    external: true

secrets:
  github_token:
    file: ./token.txt
