name: Docker Compose Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/app:latest

      - name: Set up Docker Compose
        run: |
          sudo wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d
