name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build static assets in Docker container
      - name: Build static assets
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -p codecartographer -f docker-compose.yml up -d
          # wait for a short period to ensure services are up
          sleep 10
          # retrieve container ID for the 'web' service
          container_id=$(docker-compose -p codecartographer ps -q web)
          echo "Copying static assets from container $container_id"
          docker cp "$container_id:/app" ./statics
      # Show web container logs for debugging
      - name: Show web container logs
        run: |
          container_id=$(docker-compose -p codecartographer ps -q web)
          docker logs "$container_id"
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./statics
          keep_files: true
          commit_message: 'Deploy to GitHub Pages'
